<script lang="ts">
    import { enhance } from "$app/forms";
    import { invalidateAll } from "$app/navigation";
    import Button from "$lib/components/ui/button/button.svelte";
    import * as Field from "$lib/components/ui/field/index";
    import * as Popover from "$lib/components/ui/popover/index";
    import * as Command from "$lib/components/ui/command/index";
    import * as Dialog from "$lib/components/ui/dialog/index";
    import { toast } from "svelte-sonner";
    import { Check, ChevronsUpDown } from "@lucide/svelte";
    import { cn } from "$lib/utils";

    type Student = { id: number; name: string; studentCode: string };

    let {
        open = $bindable(false),
        students = [],
        classId,
    }: {
        open: boolean;
        students: Student[];
        classId: number | string;
    } = $props();

    let isSubmitting = $state(false);
    let comboOpen = $state(false);
    let selectedStudentIds = $state<Set<number>>(new Set());

    function toggleStudent(id: number) {
        const next = new Set(selectedStudentIds);
        if (next.has(id)) next.delete(id);
        else next.add(id);
        selectedStudentIds = next;
    }

    function removeStudent(id: number) {
        const next = new Set(selectedStudentIds);
        next.delete(id);
        selectedStudentIds = next;
    }

    const selectedStudents = $derived(
        students.filter((s) => selectedStudentIds.has(s.id)),
    );

    function normalize(str: string) {
        return str
            .normalize("NFD")
            .replace(/[\u0300-\u036f]/g, "")
            .toLowerCase();
    }

    function filterStudent(value: string, search: string) {
        return normalize(value).includes(normalize(search)) ? 1 : 0;
    }

    function resetForm() {
        selectedStudentIds = new Set();
    }

    const handleSubmit: import("@sveltejs/kit").SubmitFunction = () => {
        isSubmitting = true;
        return async ({ result, update }) => {
            isSubmitting = false;
            if (result.type === "failure") {
                toast.error(
                    (result.data as any)?.message ?? "Failed to create group",
                );
            } else if (result.type === "success") {
                toast.success("Group created successfully!");
                open = false;
                resetForm();
                await invalidateAll(); // reload bảng groups thay vì goto
            }
            await update({ reset: false });
        };
    };
</script>

<Dialog.Root bind:open>
    <Dialog.Content class="max-w-2xl">
        <Dialog.Header>
            <Dialog.Title>Create New Group</Dialog.Title>
            <Dialog.Description>
                The group name and code will be
                <span class="font-semibold text-stone-700">
                    automatically generated by the system
                </span>
                once the group is created successfully.
            </Dialog.Description>
        </Dialog.Header>

        <form method="POST" action="?/createGroup" use:enhance={handleSubmit}>
            {#each [...selectedStudentIds] as id}
                <input type="hidden" name="studentIds" value={id} />
            {/each}
            <input type="hidden" name="classId" value={classId} />

            <!-- Info note -->
            <div
                class="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"
            >
                <div class="flex items-center gap-2">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="h-4 w-4 shrink-0 text-amber-500"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                    >
                        <path
                            fill-rule="evenodd"
                            d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                            clip-rule="evenodd"
                        />
                    </svg>
                    <span
                        >All fields are optional. Group name and code will be
                        auto-assigned.</span
                    >
                </div>
            </div>

            <!-- Students combobox -->
            <div class="mt-5">
                <Field.Field>
                    <Field.Label>Students</Field.Label>
                    <Popover.Root bind:open={comboOpen}>
                        <Popover.Trigger>
                            {#snippet child({ props })}
                                <Button
                                    {...props}
                                    type="button"
                                    variant="outline"
                                    role="combobox"
                                    aria-expanded={comboOpen}
                                    class="mt-1 w-full justify-between border-input font-normal text-stone-500 hover:bg-white"
                                >
                                    {selectedStudentIds.size > 0
                                        ? `${selectedStudentIds.size} student(s) selected`
                                        : "Search and select students..."}
                                    <ChevronsUpDown
                                        class="ml-2 h-4 w-4 shrink-0 opacity-50"
                                    />
                                </Button>
                            {/snippet}
                        </Popover.Trigger>

                        <Popover.Content
                            class="w-[500px] h-[250px] p-0"
                            align="start"
                            side="bottom"
                            avoidCollisions={false}
                        >
                            <Command.Root filter={filterStudent}>
                                <Command.Input
                                    placeholder="Search by name or student code..."
                                />
                                <Command.Empty>No students found.</Command.Empty
                                >
                                <Command.Group class="max-h-64 overflow-y-auto">
                                    {#each students as student}
                                        <Command.Item
                                            value={`${student.studentCode} ${student.name}`}
                                            onSelect={() =>
                                                toggleStudent(student.id)}
                                            class="cursor-pointer"
                                        >
                                            <Check
                                                class={cn(
                                                    "mr-2 h-4 w-4",
                                                    selectedStudentIds.has(
                                                        student.id,
                                                    )
                                                        ? "opacity-100 text-amber-600"
                                                        : "opacity-0",
                                                )}
                                            />
                                            <span
                                                class="font-mono text-xs text-stone-500 mr-2"
                                                >{student.studentCode}</span
                                            >
                                            <span class="text-sm text-stone-700"
                                                >{student.name}</span
                                            >
                                        </Command.Item>
                                    {/each}
                                </Command.Group>
                            </Command.Root>
                        </Popover.Content>
                    </Popover.Root>

                    {#if selectedStudents.length > 0}
                        <div class="mt-2 flex flex-wrap gap-2">
                            {#each selectedStudents as student}
                                <span
                                    class="inline-flex items-center gap-1.5 rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-800"
                                >
                                    <span class="font-mono"
                                        >{student.studentCode}</span
                                    >
                                    <span>{student.name}</span>
                                    <button
                                        type="button"
                                        class="ml-0.5 text-amber-500 hover:text-amber-700"
                                        onclick={() =>
                                            removeStudent(student.id)}>×</button
                                    >
                                </span>
                            {/each}
                        </div>
                    {/if}
                </Field.Field>
            </div>

            <Dialog.Footer class="mt-6">
                <Button
                    type="button"
                    variant="outline"
                    class="cursor-pointer border-stone-300 text-stone-600"
                    onclick={() => {
                        open = false;
                        resetForm();
                    }}
                >
                    Cancel
                </Button>
                <Button
                    type="submit"
                    disabled={isSubmitting}
                    class="cursor-pointer bg-amber-600 text-white hover:bg-amber-700 disabled:opacity-60"
                >
                    {#if isSubmitting}
                        <span
                            class="mr-2 inline-block h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent"
                        ></span>
                        Creating...
                    {:else}
                        Create Group
                    {/if}
                </Button>
            </Dialog.Footer>
        </form>
    </Dialog.Content>
</Dialog.Root>
